/* eslint-disable sort-keys-fix/sort-keys-fix */

// Documented for Presto 0.289

import type { languages } from 'monaco-editor';

export const conf: languages.LanguageConfiguration = {
  comments: {
    lineComment: '--',
    blockComment: ['/*', '*/'],
  },
  brackets: [
    ['{', '}'],
    ['[', ']'],
    ['(', ')'],
  ],
  autoClosingPairs: [
    { open: '{', close: '}' },
    { open: '[', close: ']' },
    { open: '(', close: ')' },
    { open: '"', close: '"' },
    { open: "'", close: "'" },
  ],
  surroundingPairs: [
    { open: '{', close: '}' },
    { open: '[', close: ']' },
    { open: '(', close: ')' },
    { open: '"', close: '"' },
    { open: "'", close: "'" },
  ],
};

export const language = <languages.IMonarchLanguage>{
  defaultToken: '',
  tokenPostfix: '.sql',
  ignoreCase: true,

  brackets: [
    { open: '[', close: ']', token: 'delimiter.square' },
    { open: '(', close: ')', token: 'delimiter.parenthesis' },
  ],

  keywords: [
    // https://prestodb.io/docs/current/language/reserved.html
    'ALTER',
    'AS',
    'BY',
    'CASE',
    'CAST',
    'CONSTRAINT',
    'CREATE',
    'CUBE',
    'CURRENT_DATE',
    'CURRENT_TIME',
    'CURRENT_TIMESTAMP',
    'CURRENT_USER',
    'DEALLOCATE',
    'DELETE',
    'DESCRIBE',
    'DISTINCT',
    'DROP',
    'ELSE',
    'END',
    'ESCAPE',
    'EXCEPT',
    'EXECUTE',
    'EXISTS',
    'EXTRACT',
    'FALSE',
    'FOR',
    'FROM',
    'FULL',
    'GROUP',
    'GROUPING',
    'HAVING',
    'INSERT',
    'INTO',
    /*
    // listed as functions below
    'LOCALTIME',
    'LOCALTIMESTAMP',
    */
    'NATURAL',
    'NORMALIZE',
    'ON',
    'ORDER',
    'PREPARE',
    'RECURSIVE',
    'ROLLUP',
    'SELECT',
    'TABLE',
    'THEN',
    'TRUE',
    'UESCAPE',
    'UNNEST',
    'USING',
    'VALUES',
    'WHEN',
    'WHERE',
    'WITH',
  ],
  operators: [
    'AND',
    'BETWEEN',
    'CROSS',
    'IN',
    'INNER',
    'INTERSECT',
    'IS',
    'JOIN',
    'LEFT',
    'LIKE',
    'NOT',
    'NULL',
    'OR',
    'OUTER',
    'RIGHT',
    'UNION',
  ],
  builtinFunctions: [
    // https://prestodb.io/docs/current/functions.html
    'abs',
    'acos',
    'all',
    'all_match',
    'any',
    'any_match',
    'any_value',
    'approx_distinct',
    'approx_most_frequent',
    'approx_percentile',
    'approx_set',
    'all_keys_match',
    'any_keys_match',
    'any_values_match',
    'approx_set',
    'arbitrary',
    'array_agg',
    'array_average',
    'array_cum_sum',
    'array_distinct',
    'array_duplicates',
    'array_except',
    'array_frequency',
    'array_has_duplicates',
    'array_intersect',
    'array_join',
    'array_least_frequent',
    'array_max',
    'array_max_by',
    'array_min',
    'array_min_by',
    'array_normalize',
    'array_position',
    'array_remove',
    'array_sort',
    'array_sort_desc',
    'array_split_into_chunks',
    'array_sum',
    'array_top_n',
    'array_union',
    'arrays_overlap',
    'asin',
    'atan',
    'atan2',
    'avg',
    'bar',
    'beta_cdf',
    'bing_tile',
    'bing_tile_at',
    'bing_tile_children',
    'bing_tile_coordinates',
    'bing_tile_parent',
    'bing_tile_polygon',
    'bing_tile_quadkey',
    'bing_tile_zoom_level',
    'bing_tiles_around',
    'binomial_cdf',
    'bit_count',
    'bitwise_and',
    'bitwise_and_agg',
    'bitwise_arithmetic_shift_right',
    'bitwise_left_shift',
    'bitwise_logical_shift_right',
    'bitwise_not',
    'bitwise_or',
    'bitwise_or_agg',
    'bitwise_right_shift',
    'bitwise_right_shift_arithmetic',
    'bitwise_shift_left',
    'bitwise_xor',
    'bitwise_xor_agg',
    'bool_and',
    'bool_or',
    'cardinality',
    'cast',
    'cauchy_cdf',
    'cbrt',
    'ceil',
    'ceiling',
    'char2hexint',
    'checksum',
    'chi_squared_cdf',
    'chr',
    'color',
    'classification_fall_out',
    'classification_miss_rate',
    'classification_precision',
    'classification_recall',
    'classification_thresholds',
    'coalesce',
    'codepoint',
    'combinations',
    'concat',
    'construct_tdigest',
    'contains',
    'convex_hull_agg',
    'corr',
    'cos',
    'cosh',
    'cosine_similarity',
    'count',
    'count_if',
    'covar_pop',
    'covar_samp',
    'crc32',
    'cume_dist',
    'current_timezone',
    'date',
    'date_add',
    'date_format',
    'date_diff',
    'date_parse',
    'date_trunc',
    'day',
    'day_of_month',
    'day_of_week',
    'day_of_year',
    'degrees',
    'dense_rank',
    'destructure_tdigest',
    'differential_entropy',
    'dow',
    'doy',
    'e',
    'element_at',
    'empty_apprx_set',
    'ends_with',
    'entropy',
    'every',
    'exp',
    'expand_envelope',
    'extract',
    'f_cdf',
    'filter',
    'find_first',
    'find_first_index',
    'first_value',
    'flatten',
    'flatten_geometry_collections',
    'format_datetime',
    'floor',
    'from_base',
    'from_base32',
    'from_base64',
    'from_base64url',
    'from_big_endian_32',
    'from_big_endian_64',
    'from_hex',
    'from_ieee754_32',
    'from_ieee754_64',
    'from_iso8601_date',
    'from_iso8601_timestamp',
    'from_unixtime',
    'from_utf8',
    'gamma_cdf',
    'geometric_mean',
    'geometric_mean',
    'geometric_mean',
    'geometry_as_geojson',
    'geometry_from_geojson',
    'geometry_invalid_reason',
    'geometry_nearest_points',
    'geometry_to_bing_tiles',
    'geometry_to_dissolved_bing_tiles',
    'geometry_union',
    'geometry_union_agg',
    'great_circle_distance',
    'greatest',
    'hamming_distance',
    'hash_counts',
    'histogram',
    'hmac_md5',
    'hmac_sha1',
    'hmac_sha256',
    'hmac_sha512',
    'hour',
    'index',
    'infinity',
    'intersection_cardinality',
    'inverse_beta_cdf',
    'inverse_binomial_cdf',
    'inverse_cauchy_cdf',
    'inverse_chi_squared_cdf',
    'inverse_gamma_cdf',
    'inverse_f_cdf',
    'inverse_laplace_cdf',
    'inverse_normal_cdf',
    'inverse_poisson_cdf',
    'inverse_weibull_cdf',
    'ip_prefix',
    'ip_prefix_collapse',
    'ip_subnet_max',
    'ip_subnet_min',
    'ip_subnet_of',
    'ip_subnet_range',
    'is_finite',
    'is_infinite',
    'is_json_scalar',
    'is_nan',
    'jaccard_index',
    'json_array_contains',
    'json_array_get',
    'json_array_length',
    'json_extract',
    'json_extract_scalar',
    'json_format',
    'json_parse',
    'json_size',
    'key_sampling_percent',
    'khyperloglog_agg',
    'kurtosis',
    'lag',
    'laplace_cdf',
    'last_day_of_month',
    'last_value',
    'lead',
    'least',
    'length',
    'levenshtein_distance',
    'line_interpolate_point',
    'line_locate_point',
    'ln',
    'localtime',
    'localtimestamp',
    'log2',
    'log10',
    'lower',
    'lpad',
    'ltrim',
    'make_set_digest',
    'map',
    'map_agg',
    'map_concat',
    'map_entries',
    'map_filter',
    'map_from_entries',
    'map_key_exists',
    'map_keys',
    'map_keys_by_top_n_values',
    'map_normalize',
    'map_remove_null_values',
    'map_subset',
    'map_top_n',
    'map_top_n_keys',
    'map_top_n_values',
    'map_union',
    'map_union_sum',
    'map_values',
    'map_zip_with',
    'max',
    'max_by',
    'merge',
    'merge_hll',
    'merge_khll',
    'merge_set_digest',
    'merge_sfm',
    'merge_tdigest',
    'millisecond',
    'min',
    'min_by',
    'minute',
    'month',
    'md5',
    'mod',
    'multimap_agg',
    'multimap_from_entries',
    'murmur3_x64_128',
    'myanmar_font_encoding',
    'myanmar_normalize_unicode',
    'nan',
    'ngrams',
    'no_keys_match',
    'no_values_match',
    'none_match',
    'noisy_approx_distinct_sfm',
    'noisy_approx_set_sfm',
    'noisy_approx_set_sfm_from_index_and_zeroes',
    'noisy_avg_gaussian',
    'noisy_count_gaussian',
    'noisy_count_if_gaussian',
    'noisy_empty_approx_set_sfm',
    'noisy_sum_gaussian',
    'normal_cdf',
    'normalize',
    'now',
    'nth_value',
    'ntile',
    'nullif',
    'numeric_histogram',
    'parse_datedate',
    'parse_duration',
    'parse_presto_data_size',
    'percent_rank',
    'pi',
    'pinot_binary_decimal_to_double',
    'poisson_cdf',
    'position',
    'pow',
    'power',
    'qdigest_agg',
    'quantile_at_value',
    'quarter',
    'radians',
    'rand',
    'random',
    'rank',
    'render',
    'reduce',
    'reduce_agg',
    'regexp_extract',
    'regexp_extract_all',
    'regexp_like',
    'regexp_replace',
    'regexp_split',
    'regr_avgx',
    'regr_avgy',
    'regr_count',
    'regr_intercept',
    'regr_r2',
    'regr_slope',
    'regr_sxx',
    'regr_sxy',
    'regr_syy',
    'reidentification_potential',
    'remove_nulls',
    'repeat',
    'replace',
    'replace_first',
    'reservoir_sample',
    'reverse',
    'rgb',
    'round',
    'row_number',
    'rpad',
    'rtrim',
    'scale_qdigest',
    'scale_tdigest',
    'second',
    'secure_rand',
    'secure_random',
    'sequence',
    'set_agg',
    'set_union',
    'sha1',
    'sha256',
    'sha512',
    'shuffle',
    'sign',
    'simplify_geometry',
    'sin',
    'sketch_kll',
    'sketch_kll_with_k',
    'sketch_kll_quantile',
    'sketch_kll_rank',
    'sketch_theta',
    'sketch_theta_estimate',
    'sketch_theta_summary',
    'skewness',
    'slice',
    'some',
    'substring',
    'split',
    'split_part',
    'split_to_map',
    'split_to_multimap',
    'spooky_hash_v2_32',
    'spooky_hash_v2_64',
    'sqrt',
    'ST_Area',
    'ST_AsBinary',
    'ST_AsText',
    'ST_Boundary',
    'ST_Buffer',
    'ST_Centroid',
    'ST_Contains',
    'ST_ConvexHull',
    'ST_CoordDim',
    'ST_Crosses',
    'ST_Difference',
    'ST_Dimension',
    'ST_Disjoint',
    'ST_Distance',
    'ST_Envelope',
    'ST_EnvelopeAsPts',
    'ST_Equals',
    'ST_ExteriorRing',
    'ST_Geometries',
    'ST_GeometryFromText',
    'ST_GeometryN',
    'ST_GeometryType',
    'ST_GeomFromBinary',
    'ST_EndPoint',
    'ST_InteriorRingN',
    'ST_InteriorRings',
    'ST_Intersection',
    'ST_Intersects',
    'ST_IsClosed',
    'ST_IsEmpty',
    'ST_IsRing',
    'ST_IsSimple',
    'ST_IsValid',
    'ST_Length',
    'ST_LineFromText',
    'ST_LineString',
    'ST_MultiPoint',
    'ST_NumGeometries',
    'ST_NumInteriorRing',
    'ST_NumPoints',
    'ST_Overlaps',
    'ST_Point',
    'ST_PointN',
    'ST_Points',
    'ST_Polygon',
    'ST_Relate',
    'ST_StartPoint',
    'ST_SymDifference',
    'ST_Touches',
    'ST_Union',
    'ST_Within',
    'ST_X',
    'ST_XMax',
    'ST_XMin',
    'ST_Y',
    'ST_YMax',
    'ST_YMin',
    'starts_with',
    'stddev',
    'stddev_pop',
    'stddev_samp',
    'strpos',
    'strrpos',
    'substr',
    'sum',
    'tan',
    'tanh',
    'tdigest_agg',
    'trimmed_mean',
    'transform_keys',
    'transform_values',
    'timezone_minute',
    'timezone_hour',
    'to_base',
    'to_base32',
    'to_base64',
    'to_base64url',
    'to_big_endian_32',
    'to_big_endian_64',
    'to_char',
    'to_date',
    'to_geometry',
    'to_hex',
    'to_ieee754_32',
    'to_ieee754_64',
    'to_iso8601',
    'to_milliseconds',
    'to_spherical_geography',
    'to_timestamp',
    'to_unixtime',
    'to_utf8',
    'trail',
    'transform',
    'trim',
    'trim_array',
    'truncate',
    'try',
    'try_cast',
    'typeof',
    'uniqueness_distribution',
    'upper',
    'url_encode',
    'url_extract_fragment',
    'url_extract_host',
    'url_extract_parameter',
    'url_extract_path',
    'url_extract_port',
    'url_extract_protocol',
    'url_extract_query',
    'uuid',
    'value_at_quantile',
    'values_at_quantiles',
    'var_pop',
    'var_samp',
    'variance',
    'week',
    'week_of_year',
    'weibull_cdf',
    'width_bucket',
    'wilson_interval_lower',
    'wilson_interval_upper',
    'word_stem',
    'xxhash64',
    'year',
    'year_of_week',
    'yow',
    'zip',
    'zip_with',
  ],
  builtinVariables: [
    // NOT SUPPORTED
  ],
  pseudoColumns: [
    // NOT SUPPORTED
  ],
  tokenizer: {
    root: [
      { include: '@comments' },
      { include: '@whitespace' },
      { include: '@pseudoColumns' },
      { include: '@numbers' },
      { include: '@strings' },
      { include: '@complexIdentifiers' },
      { include: '@scopes' },
      [/[;,.]/, 'delimiter'],
      [/[()]/, '@brackets'],
      [
        /[\w@#$]+/,
        {
          cases: {
            '@operators': 'operator',
            '@builtinVariables': 'predefined',
            '@builtinFunctions': 'predefined',
            '@keywords': 'keyword',
            '@default': 'identifier',
          },
        },
      ],
      [/[<>=!%&+\-*/|~^]/, 'operator'],
    ],
    whitespace: [[/\s+/, 'white']],
    comments: [
      [/--+.*/, 'comment'],
      [/\/\*/, { token: 'comment.quote', next: '@comment' }],
    ],
    comment: [
      [/[^*/]+/, 'comment'],
      // Not supporting nested comments, as nested comments seem to not be standard?
      // i.e. http://stackoverflow.com/questions/728172/are-there-multiline-comment-delimiters-in-sql-that-are-vendor-agnostic
      // [/\/\*/, { token: 'comment.quote', next: '@push' }],    // nested comment not allowed :-(
      [/\*\//, { token: 'comment.quote', next: '@pop' }],
      [/./, 'comment'],
    ],
    pseudoColumns: [
      [
        /[$][A-Za-z_][\w@#$]*/,
        {
          cases: {
            '@pseudoColumns': 'predefined',
            '@default': 'identifier',
          },
        },
      ],
    ],
    numbers: [
      [/0[xX][0-9a-fA-F]*/, 'number'],
      [/[$][+-]*\d*(\.\d*)?/, 'number'],
      [/((\d+(\.\d*)?)|(\.\d+))([eE][-+]?\d+)?/, 'number'],
    ],
    strings: [[/'/, { token: 'string', next: '@string' }]],
    string: [
      [/[^']+/, 'string'],
      [/''/, 'string'],
      [/'/, { token: 'string', next: '@pop' }],
    ],
    complexIdentifiers: [
      [/"/, { token: 'identifier.quote', next: '@quotedIdentifier' }],
    ],
    quotedIdentifier: [
      [/[^"]+/, 'identifier'],
      [/""/, 'identifier'],
      [/"/, { token: 'identifier.quote', next: '@pop' }],
    ],
    scopes: [
      // NOT SUPPORTED
    ],
  },
};
