/* eslint-disable sort-keys-fix/sort-keys-fix */

import type { languages } from 'monaco-editor';

export const conf: languages.LanguageConfiguration = {
  comments: {
    lineComment: '--',
    blockComment: ['/*', '*/'],
  },
  brackets: [
    ['{', '}'],
    ['[', ']'],
    ['(', ')'],
  ],
  autoClosingPairs: [
    { open: '{', close: '}' },
    { open: '[', close: ']' },
    { open: '(', close: ')' },
    { open: '"', close: '"' },
    { open: "'", close: "'" },
  ],
  surroundingPairs: [
    { open: '{', close: '}' },
    { open: '[', close: ']' },
    { open: '(', close: ')' },
    { open: '"', close: '"' },
    { open: "'", close: "'" },
  ],
};

export const language = <languages.IMonarchLanguage>{
  defaultToken: '',
  tokenPostfix: '.sql',
  ignoreCase: true,

  brackets: [
    { open: '[', close: ']', token: 'delimiter.square' },
    { open: '(', close: ')', token: 'delimiter.parenthesis' },
  ],

  keywords: [
    // https://prestodb.io/docs/current/language/reserved.html
    'ALTER',
    'AS',
    'BY',
    'CASE',
    'CAST',
    'CONSTRAINT',
    'CREATE',
    'CUBE',
    /*
    // listed as functions below
    'CURRENT_DATE',
    'CURRENT_TIME',
    'CURRENT_TIMESTAMP',
    */
    'CURRENT_USER',
    'DEALLOCATE',
    'DELETE',
    'DESCRIBE',
    'DISTINCT',
    'DROP',
    'ELSE',
    'END',
    'ESCAPE',
    'EXCEPT',
    'EXECUTE',
    'EXISTS',
    'EXTRACT',
    'FALSE',
    'FOR',
    'FROM',
    'FULL',
    'GROUP',
    'GROUPING',
    'HAVING',
    'INSERT',
    'INTO',
    /*
    // listed as functions below
    'LOCALTIME',
    'LOCALTIMESTAMP',
    */
    'NATURAL',
    'NORMALIZE',
    'ON',
    'ORDER',
    'PREPARE',
    'RECURSIVE',
    'ROLLUP',
    'SELECT',
    'TABLE',
    'THEN',
    'TRUE',
    'UESCAPE',
    'UNNEST',
    'USING',
    'VALUES',
    'WHEN',
    'WHERE',
    'WITH',
  ],
  operators: [
    'AND',
    'BETWEEN',
    'CROSS',
    'IN',
    'INNER',
    'INTERSECT',
    'IS',
    'JOIN',
    'LEFT',
    'LIKE',
    'NOT',
    'NULL',
    'OR',
    'OUTER',
    'RIGHT',
    'UNION',
  ],
  builtinFunctions: [
    // https://prestodb.io/docs/current/functions.html
    'abs',
    'acos',
    'all',
    'any',
    'any_value',
    'approx_distinct',
    'approx_most_frequent',
    'approx_percentile',
    'approx_set',
    'arbitrary',
    'array_agg',
    'asin',
    'atan',
    'atan2',
    'avg',
    'beta_cdf',
    'binomial_cdf',
    'bit_count',
    'bitwise_and',
    'bitwise_and_agg',
    'bitwise_arithmetic_shift_right',
    'bitwise_left_shift',
    'bitwise_logical_shift_right',
    'bitwise_not',
    'bitwise_or',
    'bitwise_or_agg',
    'bitwise_right_shift',
    'bitwise_right_shift_arithmetic',
    'bitwise_shift_left',
    'bitwise_xor',
    'bitwise_xor_agg',
    'bool_and',
    'bool_or',
    'cast',
    'cauchy_cdf',
    'cbrt',
    'ceil',
    'ceiling',
    'checksum',
    'chi_squared_cdf',
    'chr',
    'classification_fall_out',
    'classification_miss_rate',
    'classification_precision',
    'classification_recall',
    'classification_thresholds',
    'coalesce',
    'codepoint',
    'concat',
    'corr',
    'cos',
    'cosh',
    'cosine_similarity',
    'count',
    'count_if',
    'covar_pop',
    'covar_samp',
    'crc32',
    'current_date',
    'current_time',
    'current_timestamp',
    'current_timezone',
    'date',
    'date_add',
    'date_format',
    'date_diff',
    'date_parse',
    'date_trunc',
    'day',
    'day_of_month',
    'day_of_week',
    'day_of_year',
    'degrees',
    'differential_entropy',
    'dow',
    'doy',
    'e',
    'ends_with',
    'entropy',
    'every',
    'exp',
    'extract',
    'f_cdf',
    'format_datetime',
    'floor',
    'from_base',
    'from_base32',
    'from_base64',
    'from_base64url',
    'from_big_endian_32',
    'from_big_endian_64',
    'from_hex',
    'from_ieee754_32',
    'from_ieee754_64',
    'from_iso8601_date',
    'from_iso8601_timestamp',
    'from_unixtime',
    'from_utf8',
    'gamma_cdf',
    'geometric_mean',
    'geometric_mean',
    'geometric_mean',
    'greatest',
    'hamming_distance',
    'histogram',
    'hmac_md5',
    'hmac_sha1',
    'hmac_sha256',
    'hmac_sha512',
    'hour',
    'infinity',
    'inverse_beta_cdf',
    'inverse_binomial_cdf',
    'inverse_cauchy_cdf',
    'inverse_chi_squared_cdf',
    'inverse_gamma_cdf',
    'inverse_f_cdf',
    'inverse_laplace_cdf',
    'inverse_normal_cdf',
    'inverse_poisson_cdf',
    'inverse_weibull_cdf',
    'is_finite',
    'is_infinite',
    'is_json_scalar',
    'is_nan',
    'json_array_contains',
    'json_array_get',
    'json_array_length',
    'json_extract',
    'json_extract_scalar',
    'json_format',
    'json_parse',
    'json_size',
    'key_sampling_percent',
    'khyperloglog_agg',
    'kurtosis',
    'laplace_cdf',
    'last_day_of_month',
    'least',
    'length',
    'levenshtein_distance',
    'ln',
    'localtime',
    'localtimestamp',
    'log2',
    'log10',
    'lower',
    'lpad',
    'ltrim',
    'map_agg',
    'map_union',
    'map_union_sum',
    'max',
    'max_by',
    'merge',
    'millisecond',
    'min',
    'min_by',
    'minute',
    'month',
    'md5',
    'mod',
    'multimap_agg',
    'murmur3_x64_128',
    'nan',
    'normal_cdf',
    'normalize',
    'now',
    'nullif',
    'numeric_histogram',
    'parse_datedate',
    'parse_duration',
    'parse_presto_data_size',
    'pi',
    'poisson_cdf',
    'position',
    'pow',
    'power',
    'radians',
    'rand',
    'random',
    'reduce_agg',
    'regexp_extract',
    'regexp_extract_all',
    'regexp_like',
    'regexp_replace',
    'regexp_split',
    'regr_avgx',
    'regr_avgy',
    'regr_count',
    'regr_intercept',
    'regr_r2',
    'regr_slope',
    'regr_sxx',
    'regr_sxy',
    'regr_syy',
    'replace',
    'replace_first',
    'reservoir_sample',
    'reverse',
    'round',
    'rpad',
    'rtrim',
    'qdigest_agg',
    'quarter',
    'second',
    'secure_rand',
    'secure_random',
    'set_agg',
    'set_union',
    'sha1',
    'sha256',
    'sha512',
    'sign',
    'sin',
    'skewness',
    'some',
    'split',
    'split_part',
    'split_to_map',
    'split_to_multimap',
    'spooky_hash_v2_32',
    'spooky_hash_v2_64',
    'sqrt',
    'starts_with',
    'stddev',
    'stddev_pop',
    'stddev_samp',
    'strpos',
    'strrpos',
    'substr',
    'sum',
    'tan',
    'tanh',
    'timezone_minute',
    'timezone_hour',
    'to_base',
    'to_base32',
    'to_base64',
    'to_base64url',
    'to_big_endian_32',
    'to_big_endian_64',
    'to_hex',
    'to_ieee754_32',
    'to_ieee754_64',
    'to_iso8601',
    'to_milliseconds',
    'to_unixtime',
    'to_utf8',
    'trail',
    'trim',
    'truncate',
    'try',
    'try_cast',
    'typeof',
    'upper',
    'var_pop',
    'var_samp',
    'variance',
    'week',
    'week_of_year',
    'weibull_cdf',
    'width_bucket',
    'wilson_interval_lower',
    'wilson_interval_upper',
    'word_stem',
    'xxhash64',
    'year',
    'year_of_week',
    'yow',
  ],
  builtinVariables: [
    // NOT SUPPORTED
  ],
  pseudoColumns: [
    // NOT SUPPORTED
  ],
  tokenizer: {
    root: [
      { include: '@comments' },
      { include: '@whitespace' },
      { include: '@pseudoColumns' },
      { include: '@numbers' },
      { include: '@strings' },
      { include: '@complexIdentifiers' },
      { include: '@scopes' },
      [/[;,.]/, 'delimiter'],
      [/[()]/, '@brackets'],
      [
        /[\w@#$]+/,
        {
          cases: {
            '@operators': 'operator',
            '@builtinVariables': 'predefined',
            '@builtinFunctions': 'predefined',
            '@keywords': 'keyword',
            '@default': 'identifier',
          },
        },
      ],
      [/[<>=!%&+\-*/|~^]/, 'operator'],
    ],
    whitespace: [[/\s+/, 'white']],
    comments: [
      [/--+.*/, 'comment'],
      [/\/\*/, { token: 'comment.quote', next: '@comment' }],
    ],
    comment: [
      [/[^*/]+/, 'comment'],
      // Not supporting nested comments, as nested comments seem to not be standard?
      // i.e. http://stackoverflow.com/questions/728172/are-there-multiline-comment-delimiters-in-sql-that-are-vendor-agnostic
      // [/\/\*/, { token: 'comment.quote', next: '@push' }],    // nested comment not allowed :-(
      [/\*\//, { token: 'comment.quote', next: '@pop' }],
      [/./, 'comment'],
    ],
    pseudoColumns: [
      [
        /[$][A-Za-z_][\w@#$]*/,
        {
          cases: {
            '@pseudoColumns': 'predefined',
            '@default': 'identifier',
          },
        },
      ],
    ],
    numbers: [
      [/0[xX][0-9a-fA-F]*/, 'number'],
      [/[$][+-]*\d*(\.\d*)?/, 'number'],
      [/((\d+(\.\d*)?)|(\.\d+))([eE][-+]?\d+)?/, 'number'],
    ],
    strings: [[/'/, { token: 'string', next: '@string' }]],
    string: [
      [/[^']+/, 'string'],
      [/''/, 'string'],
      [/'/, { token: 'string', next: '@pop' }],
    ],
    complexIdentifiers: [
      [/"/, { token: 'identifier.quote', next: '@quotedIdentifier' }],
    ],
    quotedIdentifier: [
      [/[^"]+/, 'identifier'],
      [/""/, 'identifier'],
      [/"/, { token: 'identifier.quote', next: '@pop' }],
    ],
    scopes: [
      // NOT SUPPORTED
    ],
  },
};
